### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by Fancy2209** [PapirusDevelopmentTeam/papirus_icons#11]
It would be very nice if there could be a way to ask for icons and commit bugreports easily using somethig like the linux papirus icon theme issue templates

**Comment by varlesh** [comment]
It's easier to do it from the application. For request need know Activity launcher path.
I make [script](https://github.com/PapirusDevelopmentTeam/papirus_icons/blob/master/work/1graber.sh) for that, but it's not easy. 
Anyway need Google Accout for right work and authentification for that. And this not worked for all apps (paid apps not grabed, or not distrib or my region, or another architecture and etc)

**Comment by Fancy2209** [comment]
Just sent a report from the app then
but some apps are not from google play is that a problem?

**Comment by varlesh** [comment]
I didn’t receive your request. Try send from default gmail client or another...
About Google Play - it's not obligatory, i'm draw all icons (for F-Droid, GitHub and etc).
Icon Request mail have all needed things:
- Original icon
- Launchable activity
- Link to GooglePlay (it's not right sometime)

Example request (on mail):
![image](https://user-images.githubusercontent.com/8083855/148666710-1245e743-c813-425f-9d11-ab9ed36f30df.png)

Attached archive:
[icon_request_07_01_2022_14_23_25.zip](https://github.com/PapirusDevelopmentTeam/papirus_icons/files/7834375/icon_request_07_01_2022_14_23_25.zip)

**Comment by varlesh** [comment]
> Anyway need Google Accout for right work and authentification for that. And this not worked for all apps (paid apps not grabed, or not distrib on my region, or another architecture and etc)

This needed for script only on PC. When you know only package name, but not know acivity. Because "[googleplay tool](https://github.com/89z/googleplay)" not worked without authentification.

**Comment by varlesh** [comment]
Instruction how remove cache/data from application:
https://www.androidcentral.com/how-and-when-clear-app-cache-or-data-android

**Comment by varlesh** [comment]
If my yandex mail blocked on your country (due to sanctions) try sent to varlesh@gmail.com
PS: more users send mail icon reqests on yandex mail and this worked well.

**Comment by Fancy2209** [comment]
The example request you showed is mine

**Comment by varlesh** [comment]
Ok, it's worked ) Update will be avialable soon..
